<a href="https://colab.research.google.com/github/janesh-kiddev/janesh-kiddev/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
ar = np.array([23,3,3,3,3,3])
print(ar)
dr = np.array(45)
print(dr)

[23  3  3  3  3  3]
45


In [ ]:
darry = np.array([[1,2,3],[4,5,6]])
print(darry)
# displays the dimension
print(darry.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
k = np.array([1,2,2])
#indexing
print(k[0])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
1


In [ ]:
catch = np.array([[1, 2, 3, 4],[6, 7, 8, 9]])
#silcing
print(catch[1,1])


7


In [ ]:
#access the values from start to endpoint
np.arange(50,60,1)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
#to get the random numbers in float
np.random.uniform(5,10,size=4)

array([5.67402745, 5.68184747, 8.62094197, 7.64760531])

In [ ]:
np.random.uniform(50,60,size = 6)


array([58.40544912, 59.60193908, 50.86753032, 50.0229582 , 53.32465565,
       59.72250703])

In [ ]:
# generate random numbers in float
np.random.rand(1,2)

array([[0.54120808, 0.15708963]])

In [ ]:
np.random.random_integers(1,10)

<ipython-input-12-c8e21f3575da>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10)


2

In [ ]:
print("data type", arr.dtype)
print("matrix shape", arr.shape)
print("dimension", arr.ndim)
print("size", arr.size)
print("item size in Bytes", arr.itemsize)
print("array size in Bytes", arr.nbytes)

data type int64
matrix shape (1, 1, 1, 1, 4)
dimension 5
size 4
item size in Bytes 8
array size in Bytes 32


In [16]:
dr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(dr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
